apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  "22022": tabaratasso/sftp-service-tabaratasso:22
  "22023": avisadesconto/sftp-service-avisadesconto:22
  "59001": tabaratasso/mysql:59001
  "59002": avisadesconto/mysql-service-avisadesconto:59002
