---

apiVersion: v1
kind: Pod
metadata:
  name: create-index-pod
spec:
  containers:
  - name: create-index-container
    image: node:18-alpine  # Um contêiner leve que pode ser usado para criar arquivos   
    command: ['sh', '-c', 'while true; do sleep 3600; done']  # Mantém o pod em execução
    volumeMounts:
    - name: script-volume
      mountPath: /crawler  # Caminho dentro do pod onde será montado o PVC do crawler    
    - name: wordpress-data
      mountPath: /wordpress  # Caminho dentro do pod onde será montado o PVC principal do wordpress
  volumes:
  - name: script-volume
    persistentVolumeClaim:
      claimName: crawler-pvc  # Solicitando o volume do crawler  
  - name: wordpress-data
    persistentVolumeClaim:
      claimName: wordpress-pvc # Solicitando o volume para será será copiado o conteudo
      
