---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: wp-storageclass-teste
provisioner: ebs.csi.aws.com  # Provisionador para EBS no AWS EKS
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  fsType: ext4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc-teste
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: wp-storageclass-teste  # Referencia o StorageClass criado para EBS

