{{- if .Values.crawler.enabled }}
---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-crawler-pechinchou
  namespace: {{ .Values.namespace.name }}
spec:
  schedule: "*/45 * * * *" # A cada 10 minutos
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 1500 # 25 minutos
      template:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: {{ .Values.affinity.label }}
                    operator: In
                    values:
                    - {{ .Values.namespace.name }}          
          containers:
          - name: crawler-container
            image: node:14-alpine            
            command: ["sh", "-c", "node /crawler/pechinchou/src/index.js 20"]            
            volumeMounts:
            - name: script-volume
              mountPath: /crawler
            - name: wordpress-volume
              mountPath: /wordpress  
          restartPolicy: OnFailure
          volumes:
          - name: script-volume
            persistentVolumeClaim:
              claimName: crawler-pvc  # Substitua pelo nome do seu PVC
          - name: wordpress-volume
            persistentVolumeClaim:
              claimName: wordpress-pvc   # Substitua pelo nome do seu PVC
  concurrencyPolicy: Forbid

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-crawler-promobit
  namespace: {{ .Values.namespace.name }}
spec:
  schedule: "* 1 * * *" # A cada 30 minutos
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 240 # 2 minutos
      template:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: {{ .Values.affinity.label }}
                    operator: In
                    values:
                    - {{ .Values.namespace.name }}                
          containers:
          - name: crawler-container
            image: node:18-alpine            
            command: ["sh", "-c", "node /crawler/promobit/index.js"]            
            volumeMounts:
            - name: script-volume
              mountPath: /crawler
          restartPolicy: OnFailure
          volumes:
          - name: script-volume
            persistentVolumeClaim:
              claimName: crawler-pvc
  concurrencyPolicy: Forbid
{{- end }}