{{- if .Values.wordpress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ingress-{{ .Values.namespace.name }}
  namespace: {{ .Values.namespace.name }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
  {{- if .Values.hml.enabled }}
    - "hml.{{ .Values.namespace.name }}.com.br"
  {{- else }}
    - "{{ .Values.namespace.name }}.com.br"
  {{- end }}
  {{- if not .Values.hml.enabled }}
    - "www.{{ .Values.namespace.name }}.com.br"
  {{- end }}
    secretName: "wordpress-tls-{{ .Values.namespace.name }}"
  rules:
      {{- if .Values.hml.enabled }}
    - host: "hml.{{ .Values.namespace.name }}.com.br"
      {{- else }}
    - host: "{{ .Values.namespace.name }}.com.br" 
      {{- end }}     
      http:
        paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: wordpress-service-{{ .Values.namespace.name }}
              port:
                number: {{ .Values.wordpress.ports.servicePort }}
      {{- if not .Values.hml.enabled }}
    - host: "www.{{ .Values.namespace.name }}.com.br"      
      http:
        paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: wordpress-service-{{ .Values.namespace.name }}
              port:
                number: {{ .Values.wordpress.ports.servicePort }}
      {{- end }}
    
{{- end }}

{{- if .Values.mysql.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mysql-ingress-{{ .Values.namespace.name }}
  namespace: {{ .Values.namespace.name }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - "mysql.{{ .Values.namespace.name }}.com.br"
    secretName: "mysql-tls-{{ .Values.namespace.name }}"
  rules:
    - host: "mysql.{{ .Values.namespace.name }}.com.br"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: mysql-service-{{ .Values.namespace.name }}
                port:
                  number: {{ .Values.mysql.service.port }}
{{- end }}

{{- if .Values.sftp.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sftp-ingress
  namespace: {{ .Values.namespace.name }}
  annotations:    
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "sftp.{{ .Values.namespace.name }}.com.br"
    secretName: "sftp-tls-{{ .Values.namespace.name }}"
  rules:
    - host: "sftp.{{ .Values.namespace.name }}.com.br"
      http:
        paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: sftp-service-{{ .Values.namespace.name }}
              port:
                number: 22
{{- end }}

{{- if .Values.phpaMyAmin.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phpmyadmin-ingress-{{ .Values.namespace.name }}
  namespace: {{ .Values.namespace.name }}
  annotations:    
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "adm.{{ .Values.namespace.name }}.com.br"
    secretName: "phpmyadmin-tls-{{ .Values.namespace.name }}"
  rules:
    - host: "adm.{{ .Values.namespace.name }}.com.br"
      http:
        paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: phpmyadmin-service-{{ .Values.namespace.name }}
              port:
                number: 80
{{- end }}
