apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret-{{ .Values.namespace.name }}
  namespace: {{ .Values.namespace.name }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.secrets.MYSQL_ROOT_PASSWORD }}
  MYSQL_DATABASE: {{ .Values.mysql.secrets.MYSQL_DATABASE }}
  MYSQL_USER: {{ .Values.mysql.secrets.MYSQL_USER }}
  MYSQL_PASSWORD: {{ .Values.mysql.secrets.MYSQL_PASSWORD }}
  MYSQL_TCP_PORT: {{ .Values.mysql.secrets.MYSQL_TCP_PORT }}

{{- if .Values.sftp.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: sftp-secret-{{ .Values.namespace.name }}
  namespace: {{ .Values.namespace.name }}
type: Opaque
data:
  sftp-credentials: c2Z0cDpAYXZpc2ExMDEwOjEwMDA=
{{- end }}
