
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-storageclass-{{ .Values.namespace.name }}
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  fsType: {{ .Values.mysql.volumes.fsType }}

{{- if .Values.wordpress.storageClass.enabled }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: wp-storageclass-{{ .Values.namespace.name }}  
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  fsType: {{ .Values.wordpress.storageClass.fsType }}
{{- end }}
