apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: avisadesconto
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: YXZpczRAMTAyMCE=
  MYSQL_DATABASE: YXZpc2FkZXNjb250bw==
  MYSQL_USER: YXZpc2FkZXNjb250bw==
  MYSQL_PASSWORD: YXZpczRAMTAyMEA=
  MYSQL_TCP_PORT: NTkwMDE=

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-storageclass-avisadesconto
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  fsType: xfs

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: avisadesconto
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: biarms/mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_TCP_PORT
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_TCP_PORT
          ports:
            - containerPort: 59001
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "400m"
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
        storageClassName: mysql-storageclass-avisadesconto

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: avisadesconto
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 59001
      targetPort: 3306
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mysql-ingress
  namespace: avisadesconto
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - "mysql.avisadesconto.com.br"
    secretName: "mysql-tls"
  rules:
    - host: "mysql.avisadesconto.com.br"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: mysql
                port:
                  number: 59001