apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: avisadesconto
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin:latest
          env:
            - name: PMA_ABSOLUTE_URI
              value: "https://mysql.avisadesconto.com.br/"
            - name: PMA_HOST
              value: "mysql:59001"
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: phpmyadmin-logs
              mountPath: /var/log/phpmyadmin
      restartPolicy: Always
      volumes:
        - name: phpmyadmin-logs
          emptyDir: {}
      terminationGracePeriodSeconds: 30

---


apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: avisadesconto
spec:
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80      
  type: ClusterIP

---


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phpmyadmin-ingress
  namespace: avisadesconto
  annotations:    
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "adm.avisadesconto.com.br"
    secretName: "phpmyadmin-tls"
  rules:
    - host: "adm.avisadesconto.com.br"
      http:
        paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: phpmyadmin
              port:
                number: 80