apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: wp-storageclass-avisadesconto  
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  fsType: ext4

---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: avisadesconto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: wp-storageclass-avisadesconto  # Referencia o StorageClass criado para EBS